python lerobot/scripts/control_robot.py ^
  --robot.type=koch ^
  --control.type=record ^
  --control.single_task="put the block into the corresponding hole" ^
  --control.fps=30 ^
  --control.repo_id=shin1107/eval_koch_base_smolvla_pretrained_100000 ^
  --control.warmup_time_s=5 ^
  --control.episode_time_s=30 ^
  --control.reset_time_s=20 ^
  --control.num_episodes=80 ^
  --control.push_to_hub=false ^
  --control.policy.path=trainedmodel\models\koch_base_smolvla_pretrained\100000\pretrained_model
